name: Build

on:
  pull_request:
    branches:
      - master
      - development

env:
  ANDROID_EMULATOR_API: 34
  ANDROID_EMULATOR_ARCH: x86_64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - uses: actions/upload-artifact@v3
        with:
          name: pr
          path: pr/

      - name: Build with Gradle
        run: |
          bash ./gradlew build --stacktrace

      - name: Store APK file
        uses: actions/upload-artifact@v3
        with:
          name: apk-files
          path: |
            app/build/outputs/apk/debug/app-debug.apk

  screenshots:
    name: Screenshots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Android Screenshot Workflow
        uses: ./.github/actions/screenshot-android
        with:
          ANDROID_EMULATOR_API: ${{ env.ANDROID_EMULATOR_API }}
          ANDROID_EMULATOR_ARCH: ${{ env.ANDROID_EMULATOR_ARCH }}